name: Release
on:
  workflow_dispatch:
  push:
    paths:
      - 'VERSION'

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate environmental variables
        run: |
          echo "tag_name=$(cat VERSION)" >> $GITHUB_ENV
          echo "name=$(cat NAME)_$(cat VERSION)" >> $GITHUB_ENV
      - name: Create empty release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.tag_name }}
          body_path: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: main
          draft: false
          files: |
            VERSION
            pkg.conf
    outputs:
      release_id: ${{ steps.release.outputs.id }}
  build:
    runs-on: ubuntu-latest
    needs: prepare_release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Get revision
        run: |
          VERSION=$(cat VERSION)
          echo "revision=${VERSION#*-}" >> $GITHUB_ENV
      - name: Build
        uses: radxa-repo/bsp@main
        with:
          target: u-boot
          edition: latest
          revision: ${{ env.revision }}
          release-id: ${{ needs.prepare_release.outputs.release_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}