name: Release
on:
  workflow_dispatch:
  push:
    paths:
      - 'VERSION'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Get revision
        run: |
          VERSION=$(cat VERSION)
          echo "revision=${VERSION#*-}" >> $GITHUB_ENV
          echo "tag_name=${VERSION}" >> $GITHUB_ENV
      - name: Build
        uses: radxa-repo/bsp@main
        with:
          target: u-boot
          edition: latest
          revision: ${{ env.revision }}
      - name: Generate environmental variables
        run: |
      - name: Create release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.tag_name }}
          body_path: README.md
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: main
          draft: false
          files: |
            .output/*
            VERSION
            pkg.conf
      - name: Update Test repos
        uses: radxa-repo/update-repo-action@main
        with:
          test-repo: true
          token: ${{ secrets.RADXA_APT_TEST_REPO_TOKEN }}
